### ISSUE TITLE
Unable to produce pdf files

### ISSUE THREAD

**Issue by devarajarun** [Kalan-Lab/lsaBGC#13]
I installed and attempted to run run tests.sh, but the final plots in the see folder were not pdf files, but rather text files with values.

**Comment by raufs** [comment]
Hi, thank you for your interest in lsaBGC and giving it a try! Sorry to hear there were issues with run_tests.sh. 

Can you please share info on your operating system and when you cloned the repository? Also can you share the contents of a `Progress.log` file in one of the GCF directories for see?

Also, I am planning to make a new release today which should greatly simplify running the suite beyond the test case so would very much appreciate you giving it another try then!

**Comment by devarajarun** [comment]
Thanks for responding. The run was successful but instead of pdf files the output files were in txt format. I attached the `progress.log` and output folder screenshot. And I would like to try the new release also. 


[Progress.log](https://github.com/Kalan-Lab/lsaBGC/files/9210406/Progress.log)
![Screenshot 2022-07-28 at 17 10 00](https://user-images.githubusercontent.com/95383773/181526270-8dfa7ab6-d34e-4593-a439-5dd3a371c2ca.png)

**Comment by raufs** [comment]
Thank you for the log and screenshot! I was unable to replicate the error on a Mac, but it seems like it might be related to R not being configured properly. 

I apologize, but I just made the new release, can you please reinstall from scratch (including cloning the lsaBGC git repo and setting up the conda environment as there are new dependencies) and rerun the test. Also, to speed testing you can skip downloading annotation files until after.

Hopefully it should just work, if it doesn't please let me know and I think there are some additional tests we can run quickly to find where the issue is and patch it! 

Thank you!
Rauf

**Comment by devarajarun** [comment]
Did you get the output error on Linux? I ran it on an HPC Linux server. I'll reinstall the tool and rerun the test to see how it goes. I will let you know if there are any issues. Thanks.

**Comment by raufs** [comment]
Sounds great, let me know if the issue persists. No error on Linux, I develop and test primarily in Ubuntu myself.

**Comment by raufs** [comment]
Hi @devarajarun , thank you again for posting this issue - finally found someone with a similar issue to what you described. After  simplifying the conda environment requirements for versions of specific R libraries the problem was resolved on their laptop. Would appreciate you giving the software another try and hopefully you see the resulting PDFs this time!
