### ISSUE TITLE
Issues with lsaBGC: setup_annotation_dbs.py and Primary_Sample_Annotation_Files.txt (lsaBGC-Easy.py)

### ISSUE THREAD

**Issue by Sam-Will** [Kalan-Lab/lsaBGC#19]
Hello @raufs,

I am using lsaBGC, and I have encountered a few issues that I need a little help with. The same issues have occurred on my UNIX (Macbook) and Ubuntu (remote machine). 

Here are the issues I am facing:

1. I am having trouble downloading annotations through setup_annotation_dbs.py after TIGR04571.1.HMM. I've tried a few times with always the same issue

```
x hmm_PGAP.HMM/TIGR04571.1.HMM
Error: issues with downloading or seting up annotation database files! Please post to Github issues if unable to figure out!
```

2. When running lsaBGC-EASY.py I get an error message at step 5. I added a print statement above the error line and it looks like it's not creating Primary_Sample_Annotation_Files.txt. I've had a dig around in lsaBGC-Ready.py and potentially this is an issue arising from the code block from line 453 but it's slightly beyond my abilities

```
Checking file path: /home/samw/lsaBGC/lsaBGC_for_Kitasatospora/lsaBGC_Ready_Results/Final_Results/Primary_Sample_Annotation_Files.txt
Traceback (most recent call last):
  File "/home/samw/lsaBGC/workflows/lsaBGC-Easy.py", line 722, in runCmdViaSubprocess
    assert (os.path.isfile(cf))
AssertionError
.......
RuntimeError: Had an issue running: lsaBGC-Ready.py -i /Users/sw17073/lsaBGC/lsaBGC_for_Kitasatospora/Primary_Genomes.txt -l /Users/sw17073/lsaBGC/lsaBGC_for_Kitasatospora/BGCs_in_Primary_Genomes.txt -o /Users/sw17073/lsaBGC/lsaBGC_for_Kitasatospora/lsaBGC_Ready_Results/ -c 8 -p GECCO -m GENOME_WIDE -lc -lci 4.0 -lcj 20.0 -lcr 0.7 -a
```

Please let me know if you need any further information or if there's something I can try on my end to resolve these issues.

Thanks,
Sam

**Comment by raufs** [comment]
Thank you so much for reporting this Sam! Appreciate it a ton! 

Wow, I had introduced new code into the `setup_annotation_dbs.py` script but performed my testing of the suite without annotation databases being downloaded as of recently.  

Issue is now corrected - so if you pull the new code and then rerun setup annotations as the following:

```
# in lsaBGC git repo
git pull origin

# try downloading databases again
setup_annotation_dbs.py
```

It should complete successfully and then you can just restart your lsaBGC-Easy command same as before and it should pickup at the lsaBGC-Ready step (but unfortunately will need to rerun OrthoFinder).

I bumped up the version to 1.35.1 and confirmed that with broken databases there are issues in lsaBGC-Ready.py similar to what you describe - will definitely be adding more code to catch this in the next release. Testing on mac and unix shows it should be resolved.

Thank you again for catching this and please let me know if there are any more issues!
Rauf

**Comment by raufs** [comment]
Turns out the recent versions of the tar file with the PGAP HMMs apparently changed their directory structure. Am working on developing a Docker container for lsaBGC-Easy to have these type of update be less of an impact.

Thank you a ton for catching this and reporting it, was also affecting another program where PGAP is used for annotation! 

I also updated to v1.36 just now - mainly slight updates to the lsaBGC-Easy workflow around checking if you have too many genomes post-dereplication (if performed) to run OrthoFinder. You should still be able to restart where lsaBGC-Easy left off after pulling the recent version. 

Rauf

**Comment by SamWilliamsUOB** [comment]
Hey Rauf, 

Thanks for sorting this out and for the detailed reply! I downloaded it and I've run a few different lsaBGC-Easy.py pipelines that have worked successfully.

Weirdly the second problem seems to be fairly specific to this one genus I'm trying to work with, I've tried it several times with the same problem on different machines

```lsaBGC-Easy.py -n "Kitasatospora" -c 28 -o lsaBGC_for_Kitasatospora/```

```
--------------------
Step 5
--------------------
Beginning clustering of BGCs using either lsaBGC-Cluster (default) or BiG-SCAPE (can be requested).
Traceback (most recent call last):
  File "/home/samw/lsaBGC/workflows/lsaBGC-Easy.py", line 733, in runCmdViaSubprocess
    assert (os.path.isfile(cf))
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samw/micromamba/envs/lsaBGC/bin/lsaBGC-Easy.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/samw/lsaBGC/workflows/lsaBGC-Easy.py", line 802, in <module>
    lsaBGC_Easy()
  File "/home/samw/lsaBGC/workflows/lsaBGC-Easy.py", line 637, in lsaBGC_Easy
    runCmdViaSubprocess(lsabgc_ready_cmd, logObject,
  File "/home/samw/lsaBGC/workflows/lsaBGC-Easy.py", line 740, in runCmdViaSubprocess
    raise RuntimeError('Had an issue running: %s' % ' '.join(cmd))
RuntimeError: Had an issue running: lsaBGC-Ready.py -i /home/samw/lsaBGC_for_Kitasatospora/Primary_Genomes.txt -l /home/samw/lsaBGC_for_Kitasatospora/BGCs_in_Primary_Genomes.txt -o /home/samw/lsaBGC_for_Kitasatospora/lsaBGC_Ready_Results/ -c 28 -p GECCO -m GENOME_WIDE -lc -lci 4.0 -lcj 20.0 -lcr 0.7 -a```

All the best,
Sam

**Comment by raufs** [comment]
Hi Sam,

Thanks for sharing! Looks like this issue is related to mapping BGCs to genomes in lsaBGC-Ready. To make this function less dependent on the type of software used for BGC predictions (e.g. antismash, gecco, or deepbgc), sequences from the BGC are mapped to the genome to determine location.

I realized recently that this approach is not ideal for at least a couple reasons:

(i) antiSMASH performs sanitation which can cause the BGC sequence in the GenBank to not map 100% to the genome.
(ii) sometimes, even at the 100% identity requirement, you get BGCs mapping to multiple spots in the genome. 

Such unexpected cases were previously documented and ignored, but the logic had a lapse which led to the specific error. It seems there was two identical BGCs in one genome (18kb) which might be due to a very recent duplication or potentially an assembly error.

I am planning on addressing this by just developing individual parsers for each of the different software in the next release of lsaBGC - which I will try to have out in the next couple days.

Thanks again,
Rauf

**Comment by SamWilliamsUOB** [comment]
Hi Rauf,

Thanks for the rapid response and the explanation. Cool, it doesn't actually affect my current analysis but thought I'd flag it anyway!

Thanks for all your hard work,
Sam

**Comment by raufs** [comment]
Hi Sam,

New and improved code to determine coordinates of BGCs now available that should fix this issue! 

Sorry for the delay, was working out the new Docker setup - if you have Docker installed - the lsaBGC image is pretty large ~21 Gb, but lets you run antiSMASH in the lsaBGC-Easy workflow automatically - similar to GECCO (the default BGC prediction software) with the conda based install. 

Thanks again for reporting!
Rauf
